<svelte:head>
  <title>Snackbars - SMUI</title>
</svelte:head>

<section>
  <h2>Snackbars</h2>

  <div>
    <Snackbar bind:this={mySnackbar}>
      <Label>This is a snackbar.</Label>
    </Snackbar>

    <Snackbar bind:this={mySnackbarB}>
      <Label>This is a snackbar.</Label>
      <Actions>
        <IconButton class="material-icons" title="Dismiss">close</IconButton>
      </Actions>
    </Snackbar>

    <Button on:click={() => mySnackbar.open()}><Label>Open Snackbar</Label></Button>
    <Button on:click={() => mySnackbarB.open()}><Label>Open Snackbar With Dismiss</Label></Button>
  </div>

  <div>
    Leading with Action:

    <Snackbar leading bind:this={leadingSnackbar} on:MDCSnackbar:closed={handleClosedLeading}>
      <Label>This is a leading snackbar.</Label>
      <Actions>
        <Button>Action</Button>
      </Actions>
    </Snackbar>

    <Button on:click={() => leadingSnackbar.open()}><Label>Open Snackbar</Label></Button>
  </div>

  <pre class="status">Closed Reason: {leadingReason}</pre>

  <div>
    Stacked with Action:

    <Snackbar variant="stacked" bind:this={stackedSnackbar} on:MDCSnackbar:closed={handleClosedStacked}>
      <Label>This is a stacked snackbar. Use it when you have really long text.</Label>
      <Actions>
        <Button on:click={() => stackedAction = 'Something'}>Something</Button>
        <Button on:click={() => stackedAction = 'Another'}>Another</Button>
        <IconButton on:click={() => stackedAction = 'Dismissed'} class="material-icons" title="Dismiss">close</IconButton>
      </Actions>
    </Snackbar>

    <Button on:click={() => stackedSnackbar.open()}><Label>Open Snackbar</Label></Button>
  </div>

  <pre class="status">Closed Reason: {stackedReason}</pre>
  <pre class="status">Action: {stackedAction}</pre>

  <div>
    Using dynamic text: <br />

    <Snackbar bind:this={dynSnackbar} labelText={dynText}>
      <Label></Label>
    </Snackbar>

    <Textfield bind:value={dynText} label="Dynamic Text" input$required />

    <Button on:click={() => dynSnackbar && dynSnackbar.open()}><Label>Open Snackbar</Label></Button>
  </div>

  <div>
    The "Kitchen" Snackbar generator:

    <Kitchen bind:this={kitchen} dismiss$class="material-icons" />

    <Button on:click={pushToKitchen}><Label>Push Snackbar</Label></Button>
  </div>

  <pre class="status">Closed Reason: {kitchenReason}</pre>
  <pre class="status">Action: {kitchenAction}</pre>
</section>

<script>
  import Snackbar, {Actions, Label} from '@smui/snackbar';
  import Kitchen from '@smui/snackbar/kitchen/index';
  import Button from '@smui/button';
  import IconButton from '@smui/icon-button';
  import Textfield from '@smui/textfield';

  let mySnackbar;
  let mySnackbarB;
  let leadingSnackbar;
  let leadingReason = 'nothing yet';
  let stackedSnackbar;
  let stackedReason = 'nothing yet';
  let stackedAction = 'nothing yet';
  let dynSnackbar;
  let dynText = 'This is a snackbar with dynamic text.';
  let kitchen;
  let kitchenReason = 'nothing yet';
  let kitchenAction = 'nothing yet';

  function handleClosedLeading(e) {
    leadingReason = e.detail.reason;
  }

  function handleClosedStacked(e) {
    stackedReason = e.detail.reason;
  }

  function pushToKitchen() {
    kitchen.push({
      props: {
        variant: 'stacked'
      },
      label: 'This is a snackbar generated by the kitchen.',
      actions: [
        {
          onClick: () => kitchenAction = 'Something',
          text: 'Something'
        },
        {
          onClick: () => kitchenAction = 'Another',
          text: 'Another'
        }
      ],
      dismissButton: true,
      onDismiss: () => kitchenAction = 'Dismissed',
      onClose: e => {
        kitchenReason = e.detail.reason;
      }
    });
  }
</script>